-- Ajouter les traductions manquantes pour les pages de destination et d'authentification
INSERT INTO ui_translations (key, language, value) VALUES
-- Page de destination
('loading_destination', 'fr', 'Chargement de la destination...'),
('loading_destination', 'en', 'Loading destination...'),
('loading_destination', 'de', 'Reiseziel wird geladen...'),
('destination_not_found', 'fr', 'Destination non trouvée'),
('destination_not_found', 'en', 'Destination not found'),
('destination_not_found', 'de', 'Reiseziel nicht gefunden'),
('destination_not_available', 'fr', 'Cette destination n''existe pas ou n''est pas encore disponible.'),
('destination_not_available', 'en', 'This destination does not exist or is not yet available.'),
('destination_not_available', 'de', 'Dieses Reiseziel existiert nicht oder ist noch nicht verfügbar.'),
('explore_city', 'fr', 'Explorez'),
('explore_city', 'en', 'Explore'),
('explore_city', 'de', 'Erkunden'),
('journeys_available', 'fr', 'parcours'),
('journeys_available', 'en', 'journeys'),
('journeys_available', 'de', 'Touren'),
('explorers', 'fr', 'explorateurs'),
('explorers', 'en', 'explorers'),
('explorers', 'de', 'Entdecker'),
('points', 'fr', 'points'),
('points', 'en', 'points'),
('points', 'de', 'Punkte'),
('top_explorers', 'fr', 'Top Explorateurs'),
('top_explorers', 'en', 'Top Explorers'),
('top_explorers', 'de', 'Top Entdecker'),
('first_explorer', 'fr', 'Premier !'),
('first_explorer', 'en', 'First one!'),
('first_explorer', 'de', 'Erster!'),
('ai_personalized_journey', 'fr', 'Parcours IA Personnalisé'),
('ai_personalized_journey', 'en', 'Personalized AI Journey'),
('ai_personalized_journey', 'de', 'Personalisierte KI-Tour'),
('ai_journey_description', 'fr', 'Créez un parcours adapté à vos préférences et disponibilités'),
('ai_journey_description', 'en', 'Create a journey adapted to your preferences and availability'),
('ai_journey_description', 'de', 'Erstellen Sie eine Tour, die auf Ihre Vorlieben und Verfügbarkeit zugeschnitten ist'),
('quick_generation', 'fr', 'Génération rapide'),
('quick_generation', 'en', 'Quick generation'),
('quick_generation', 'de', 'Schnelle Generierung'),
('100_personalized', 'fr', '100% personnalisé'),
('100_personalized', 'en', '100% personalized'),
('100_personalized', 'de', '100% personalisiert'),
('filter_by_category', 'fr', 'Filtrer par catégorie'),
('filter_by_category', 'en', 'Filter by category'),
('filter_by_category', 'de', 'Nach Kategorie filtern'),
('all_journeys', 'fr', 'Tous les parcours'),
('all_journeys', 'en', 'All journeys'),
('all_journeys', 'de', 'Alle Touren'),
('no_journeys_available', 'fr', 'Aucun parcours disponible'),
('no_journeys_available', 'en', 'No journeys available'),
('no_journeys_available', 'de', 'Keine Touren verfügbar'),
('no_journeys_category', 'fr', 'Aucun parcours pour cette catégorie.'),
('no_journeys_category', 'en', 'No journeys for this category.'),
('no_journeys_category', 'de', 'Keine Touren für diese Kategorie.'),
('no_journeys_general', 'fr', 'Aucun parcours disponible pour le moment.'),
('no_journeys_general', 'en', 'No journeys available at the moment.'),
('no_journeys_general', 'de', 'Momentan sind keine Touren verfügbar.'),
('use_ai_generator', 'fr', 'Utilisez le générateur IA pour créer votre parcours !'),
('use_ai_generator', 'en', 'Use the AI generator to create your journey!'),
('use_ai_generator', 'de', 'Verwenden Sie den KI-Generator, um Ihre Tour zu erstellen!'),

-- Page d'authentification
('welcome_to_ciara', 'fr', 'Bienvenue sur CIARA'),
('welcome_to_ciara', 'en', 'Welcome to CIARA'),
('welcome_to_ciara', 'de', 'Willkommen bei CIARA'),
('your_adventure_starts', 'fr', 'Votre aventure commence ici'),
('your_adventure_starts', 'en', 'Your adventure starts here'),
('your_adventure_starts', 'de', 'Ihr Abenteuer beginnt hier'),
('back_to_home', 'fr', 'Retour à l''accueil'),
('back_to_home', 'en', 'Back to home'),
('back_to_home', 'de', 'Zurück zur Startseite'),
('loading', 'fr', 'Chargement...'),
('loading', 'en', 'Loading...'),
('loading', 'de', 'Wird geladen...'),
('sign_in', 'fr', 'Connexion'),
('sign_in', 'en', 'Sign In'),
('sign_in', 'de', 'Anmelden'),
('sign_up', 'fr', 'Inscription'),
('sign_up', 'en', 'Sign Up'),
('sign_up', 'de', 'Registrieren'),
('sign_in_title', 'fr', 'Connectez-vous'),
('sign_in_title', 'en', 'Sign In'),
('sign_in_title', 'de', 'Anmelden'),
('sign_in_subtitle', 'fr', 'Accédez à votre compte CIARA'),
('sign_in_subtitle', 'en', 'Access your CIARA account'),
('sign_in_subtitle', 'de', 'Zugriff auf Ihr CIARA-Konto'),
('email', 'fr', 'Email'),
('email', 'en', 'Email'),
('email', 'de', 'E-Mail'),
('password', 'fr', 'Mot de passe'),
('password', 'en', 'Password'),
('password', 'de', 'Passwort'),
('email_placeholder', 'fr', 'votre@email.com'),
('email_placeholder', 'en', 'your@email.com'),
('email_placeholder', 'de', 'ihre@email.com'),
('password_placeholder', 'fr', '••••••••'),
('password_placeholder', 'en', '••••••••'),
('password_placeholder', 'de', '••••••••'),
('signing_in', 'fr', 'Connexion...'),
('signing_in', 'en', 'Signing in...'),
('signing_in', 'de', 'Anmeldung...'),
('connect', 'fr', 'Se connecter'),
('connect', 'en', 'Sign in'),
('connect', 'de', 'Anmelden'),
('forgot_password', 'fr', 'Mot de passe oublié ?'),
('forgot_password', 'en', 'Forgot password?'),
('forgot_password', 'de', 'Passwort vergessen?'),
('reset_password', 'fr', 'Réinitialiser le mot de passe'),
('reset_password', 'en', 'Reset password'),
('reset_password', 'de', 'Passwort zurücksetzen'),
('reset_password_instruction', 'fr', 'Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.'),
('reset_password_instruction', 'en', 'Enter your email address and we will send you a link to reset your password.'),
('reset_password_instruction', 'de', 'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.'),
('email_address', 'fr', 'Adresse email'),
('email_address', 'en', 'Email address'),
('email_address', 'de', 'E-Mail-Adresse'),
('cancel', 'fr', 'Annuler'),
('cancel', 'en', 'Cancel'),
('cancel', 'de', 'Abbrechen'),
('sending', 'fr', 'Envoi...'),
('sending', 'en', 'Sending...'),
('sending', 'de', 'Senden...'),
('send_link', 'fr', 'Envoyer le lien'),
('send_link', 'en', 'Send link'),
('send_link', 'de', 'Link senden'),
('create_account', 'fr', 'Créer un compte'),
('create_account', 'en', 'Create account'),
('create_account', 'de', 'Konto erstellen'),
('join_ciara_community', 'fr', 'Rejoignez la communauté CIARA'),
('join_ciara_community', 'en', 'Join the CIARA community'),
('join_ciara_community', 'de', 'Treten Sie der CIARA-Community bei'),
('first_name', 'fr', 'Prénom'),
('first_name', 'en', 'First name'),
('first_name', 'de', 'Vorname'),
('last_name', 'fr', 'Nom'),
('last_name', 'en', 'Last name'),
('last_name', 'de', 'Nachname'),
('first_name_placeholder', 'fr', 'Prénom'),
('first_name_placeholder', 'en', 'First name'),
('first_name_placeholder', 'de', 'Vorname'),
('last_name_placeholder', 'fr', 'Nom'),
('last_name_placeholder', 'en', 'Last name'),
('last_name_placeholder', 'de', 'Nachname'),
('confirm_password', 'fr', 'Confirmer le mot de passe'),
('confirm_password', 'en', 'Confirm password'),
('confirm_password', 'de', 'Passwort bestätigen'),
('passwords_not_match', 'fr', 'Les mots de passe ne correspondent pas'),
('passwords_not_match', 'en', 'Passwords do not match'),
('passwords_not_match', 'de', 'Passwörter stimmen nicht überein'),
('signing_up', 'fr', 'Inscription...'),
('signing_up', 'en', 'Signing up...'),
('signing_up', 'de', 'Registrierung...'),
('create_my_account', 'fr', 'Créer mon compte'),
('create_my_account', 'en', 'Create my account'),
('create_my_account', 'de', 'Mein Konto erstellen'),
('terms_privacy_text', 'fr', 'En vous inscrivant, vous acceptez nos'),
('terms_privacy_text', 'en', 'By signing up, you accept our'),
('terms_privacy_text', 'de', 'Mit der Registrierung akzeptieren Sie unsere'),
('terms_of_use', 'fr', 'conditions d''utilisation'),
('terms_of_use', 'en', 'terms of use'),
('terms_of_use', 'de', 'Nutzungsbedingungen'),
('and_our', 'fr', 'et notre'),
('and_our', 'en', 'and our'),
('and_our', 'de', 'und unsere'),
('privacy_policy', 'fr', 'politique de confidentialité'),
('privacy_policy', 'en', 'privacy policy'),
('privacy_policy', 'de', 'Datenschutzrichtlinie'),

-- Messages d'erreur pour l'authentification
('email_required', 'fr', 'Email requis'),
('email_required', 'en', 'Email required'),
('email_required', 'de', 'E-Mail erforderlich'),
('enter_email', 'fr', 'Veuillez entrer votre adresse email'),
('enter_email', 'en', 'Please enter your email address'),
('enter_email', 'de', 'Bitte geben Sie Ihre E-Mail-Adresse ein'),
('email_sent', 'fr', 'Email envoyé !'),
('email_sent', 'en', 'Email sent!'),
('email_sent', 'de', 'E-Mail gesendet!'),
('check_email_reset', 'fr', 'Vérifiez votre boîte mail pour réinitialiser votre mot de passe'),
('check_email_reset', 'en', 'Check your mailbox to reset your password'),
('check_email_reset', 'de', 'Überprüfen Sie Ihr Postfach, um Ihr Passwort zurückzusetzen'),
('error', 'fr', 'Erreur'),
('error', 'en', 'Error'),
('error', 'de', 'Fehler'),
('cannot_send_reset_email', 'fr', 'Impossible d''envoyer l''email de réinitialisation'),
('cannot_send_reset_email', 'en', 'Unable to send reset email'),
('cannot_send_reset_email', 'de', 'Zurücksetzungs-E-Mail kann nicht gesendet werden')

ON CONFLICT (key, language) DO NOTHING;