-- Add generation criteria and metadata to user_journey_progress table
ALTER TABLE user_journey_progress 
ADD COLUMN generation_criteria JSONB,
ADD COLUMN generated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN generation_source TEXT DEFAULT 'manual';

-- Add comments for documentation
COMMENT ON COLUMN user_journey_progress.generation_criteria IS 'Stores the criteria used to generate AI journeys (duration, difficulty, interests, etc.)';
COMMENT ON COLUMN user_journey_progress.generated_at IS 'Timestamp when the journey was generated by AI';
COMMENT ON COLUMN user_journey_progress.generation_source IS 'Source of journey creation: manual, ai_generated, etc.';