-- Add chat translations to UI translations
INSERT INTO ui_translations (key, language, value) VALUES
-- Welcome messages
('chat.welcome.default', 'fr', '🤖 Salut ! Je suis CIARA, votre guide intelligent pour {{cityName}} !'),
('chat.welcome.default', 'en', '🤖 Hello! I''m CIARA, your smart guide for {{cityName}}!'),
('chat.welcome.default', 'de', '🤖 Hallo! Ich bin CIARA, Ihr intelligenter Reiseführer für {{cityName}}!'),
('chat.welcome.destination', 'fr', 'votre destination'),
('chat.welcome.destination', 'en', 'your destination'),
('chat.welcome.destination', 'de', 'Ihr Reiseziel'),
('chat.welcome.journey_step', 'fr', '🎯 Super ! Vous êtes sur le parcours "{{journeyName}}". Je vais vous aider avec l''étape "{{stepName}}". Que puis-je faire pour vous ?'),
('chat.welcome.journey_step', 'en', '🎯 Great! You''re on the "{{journeyName}}" journey. I''ll help you with the "{{stepName}}" step. What can I do for you?'),
('chat.welcome.journey_step', 'de', '🎯 Großartig! Sie sind auf der "{{journeyName}}" Reise. Ich helfe Ihnen mit dem Schritt "{{stepName}}". Was kann ich für Sie tun?'),
('chat.welcome.journey_selected', 'fr', '🗺️ Excellent choix avec "{{journeyName}}" ! Je connais ce parcours par cœur. Comment puis-je vous aider à le préparer ?'),
('chat.welcome.journey_selected', 'en', '🗺️ Excellent choice with "{{journeyName}}"! I know this journey by heart. How can I help you prepare?'),
('chat.welcome.journey_selected', 'de', '🗺️ Ausgezeichnete Wahl mit "{{journeyName}}"! Ich kenne diese Route auswendig. Wie kann ich Ihnen bei der Vorbereitung helfen?'),

-- Step suggestions
('chat.step.history', 'fr', 'Raconte-moi l''histoire de {{stepName}}'),
('chat.step.history', 'en', 'Tell me about the history of {{stepName}}'),
('chat.step.history', 'de', 'Erzählen Sie mir die Geschichte von {{stepName}}'),
('chat.step.directions', 'fr', 'Comment me rendre à cette étape ?'),
('chat.step.directions', 'en', 'How do I get to this step?'),
('chat.step.directions', 'de', 'Wie komme ich zu diesem Schritt?'),
('chat.step.nearby', 'fr', 'Quels sont les points d''intérêt à proximité ?'),
('chat.step.nearby', 'en', 'What are the points of interest nearby?'),
('chat.step.nearby', 'de', 'Was sind die Sehenswürdigkeiten in der Nähe?'),
('chat.step.quiz_help', 'fr', 'Aide-moi avec le quiz de cette étape'),
('chat.step.quiz_help', 'en', 'Help me with this step''s quiz'),
('chat.step.quiz_help', 'de', 'Helfen Sie mir mit dem Quiz dieses Schritts'),

-- Journey suggestions
('chat.journey.history', 'fr', 'Raconte-moi l''histoire de ce parcours'),
('chat.journey.history', 'en', 'Tell me about this journey''s history'),
('chat.journey.history', 'de', 'Erzählen Sie mir die Geschichte dieser Reise'),
('chat.journey.best_time', 'fr', 'Quels sont les meilleurs moments pour faire ce parcours ?'),
('chat.journey.best_time', 'en', 'What are the best times to do this journey?'),
('chat.journey.best_time', 'de', 'Was sind die besten Zeiten für diese Reise?'),
('chat.journey.restaurants', 'fr', 'Y a-t-il des restaurants recommandés sur le trajet ?'),
('chat.journey.restaurants', 'en', 'Are there recommended restaurants on the route?'),
('chat.journey.restaurants', 'de', 'Gibt es empfohlene Restaurants auf der Route?'),
('chat.journey.optimize_points', 'fr', 'Comment optimiser mes points ?'),
('chat.journey.optimize_points', 'en', 'How to optimize my points?'),
('chat.journey.optimize_points', 'de', 'Wie optimiere ich meine Punkte?'),

-- General suggestions
('chat.general.recommend_journeys', 'fr', 'Quels parcours me recommandes-tu ?'),
('chat.general.recommend_journeys', 'en', 'Which journeys do you recommend?'),
('chat.general.recommend_journeys', 'de', 'Welche Reisen empfehlen Sie?'),
('chat.general.points_system', 'fr', 'Comment fonctionne le système de points ?'),
('chat.general.points_system', 'en', 'How does the points system work?'),
('chat.general.points_system', 'de', 'Wie funktioniert das Punktesystem?'),
('chat.general.rewards', 'fr', 'Où trouver les meilleures récompenses ?'),
('chat.general.rewards', 'en', 'Where to find the best rewards?'),
('chat.general.rewards', 'de', 'Wo finde ich die besten Belohnungen?'),
('chat.general.visit_city', 'fr', 'Que visiter à {{cityName}} ?'),
('chat.general.visit_city', 'en', 'What to visit in {{cityName}}?'),
('chat.general.visit_city', 'de', 'Was kann man in {{cityName}} besuchen?'),
('chat.general.here', 'fr', 'ici'),
('chat.general.here', 'en', 'here'),
('chat.general.here', 'de', 'hier'),

-- UI elements
('chat.quick_actions', 'fr', 'Actions rapides'),
('chat.quick_actions', 'en', 'Quick actions'),
('chat.quick_actions', 'de', 'Schnelle Aktionen'),
('chat.suggestions', 'fr', 'Suggestions'),
('chat.suggestions', 'en', 'Suggestions'),
('chat.suggestions', 'de', 'Vorschläge'),
('chat.placeholder.step', 'fr', 'Posez votre question sur l''étape...'),
('chat.placeholder.step', 'en', 'Ask your question about the step...'),
('chat.placeholder.step', 'de', 'Stellen Sie Ihre Frage zum Schritt...'),
('chat.placeholder.general', 'fr', 'Posez votre question...'),
('chat.placeholder.general', 'en', 'Ask your question...'),
('chat.placeholder.general', 'de', 'Stellen Sie Ihre Frage...'),

-- Actions
('chat.action.find_location', 'fr', 'Aide-moi à trouver {{stepName}}'),
('chat.action.find_location', 'en', 'Help me find {{stepName}}'),
('chat.action.find_location', 'de', 'Helfen Sie mir {{stepName}} zu finden'),
('chat.action.locate', 'fr', 'Localiser'),
('chat.action.locate', 'en', 'Locate'),
('chat.action.locate', 'de', 'Lokalisieren'),
('chat.action.tell_history', 'fr', 'Raconte-moi l''histoire de {{stepName}}'),
('chat.action.tell_history', 'en', 'Tell me about the history of {{stepName}}'),
('chat.action.tell_history', 'de', 'Erzählen Sie mir die Geschichte von {{stepName}}'),
('chat.action.history', 'fr', 'Histoire'),
('chat.action.history', 'en', 'History'),
('chat.action.history', 'de', 'Geschichte'),

-- Errors
('chat.error.service_unavailable', 'fr', 'Service indisponible'),
('chat.error.service_unavailable', 'en', 'Service unavailable'),
('chat.error.service_unavailable', 'de', 'Service nicht verfügbar'),
('chat.error.no_response', 'fr', 'Je ne peux pas répondre pour le moment.'),
('chat.error.no_response', 'en', 'I can''t respond at the moment.'),
('chat.error.no_response', 'de', 'Ich kann im Moment nicht antworten.'),
('chat.error.technical_difficulties', 'fr', 'Je rencontre des difficultés techniques. Essayez de reformuler votre question ou réessayez plus tard.'),
('chat.error.technical_difficulties', 'en', 'I''m experiencing technical difficulties. Try rephrasing your question or try again later.'),
('chat.error.technical_difficulties', 'de', 'Ich habe technische Schwierigkeiten. Versuchen Sie, Ihre Frage umzuformulieren oder versuchen Sie es später erneut.'),
('chat.error.title', 'fr', 'Erreur de chat'),
('chat.error.title', 'en', 'Chat error'),
('chat.error.title', 'de', 'Chat-Fehler'),
('chat.error.description', 'fr', 'Le service de chat est temporairement indisponible.'),
('chat.error.description', 'en', 'The chat service is temporarily unavailable.'),
('chat.error.description', 'de', 'Der Chat-Service ist vorübergehend nicht verfügbar.')

ON CONFLICT (key, language) DO UPDATE SET 
value = EXCLUDED.value,
updated_at = now();