-- Add missing translations for JourneyPreferencesForm

-- French translations
INSERT INTO ui_translations (key, language, value) VALUES
('desired_duration', 'fr', 'Durée souhaitée'),
('choose_duration', 'fr', 'Choisir une durée'),
('1_hour', 'fr', '1 heure'),
('2_hours', 'fr', '2 heures'),
('3_hours', 'fr', '3 heures'),
('4_hours', 'fr', '4 heures'),
('full_day', 'fr', 'Journée complète'),
('interests', 'fr', 'Centres d''intérêt'),
('difficulty_level', 'fr', 'Niveau de difficulté'),
('choose_difficulty', 'fr', 'Choisir la difficulté'),
('easy_walk', 'fr', 'Facile - Marche tranquille'),
('moderate_walk', 'fr', 'Modéré - Marche active'),
('difficult_hike', 'fr', 'Difficile - Randonnée'),
('group_size', 'fr', 'Taille du groupe'),
('optional', 'fr', 'Optionnel'),
('solo', 'fr', 'Solo'),
('couple', 'fr', 'En couple'),
('family', 'fr', 'En famille'),
('group', 'fr', 'En groupe'),
('start_location', 'fr', 'Point de départ (optionnel)'),
('start_location_placeholder', 'fr', 'Ex: Gare, Place principale...'),
('history', 'fr', 'Histoire'),
('culture', 'fr', 'Culture'),
('nature', 'fr', 'Nature'),
('gastronomy', 'fr', 'Gastronomie'),
('architecture', 'fr', 'Architecture'),
('art', 'fr', 'Art'),
('shopping', 'fr', 'Shopping'),
('nightlife', 'fr', 'Vie nocturne')
ON CONFLICT (key, language) DO UPDATE SET
value = EXCLUDED.value,
updated_at = now();

-- English translations
INSERT INTO ui_translations (key, language, value) VALUES
('desired_duration', 'en', 'Desired Duration'),
('choose_duration', 'en', 'Choose duration'),
('1_hour', 'en', '1 hour'),
('2_hours', 'en', '2 hours'),
('3_hours', 'en', '3 hours'),
('4_hours', 'en', '4 hours'),
('full_day', 'en', 'Full day'),
('interests', 'en', 'Interests'),
('difficulty_level', 'en', 'Difficulty Level'),
('choose_difficulty', 'en', 'Choose difficulty'),
('easy_walk', 'en', 'Easy - Leisurely walk'),
('moderate_walk', 'en', 'Moderate - Active walk'),
('difficult_hike', 'en', 'Difficult - Hiking'),
('group_size', 'en', 'Group Size'),
('optional', 'en', 'Optional'),
('solo', 'en', 'Solo'),
('couple', 'en', 'Couple'),
('family', 'en', 'Family'),
('group', 'en', 'Group'),
('start_location', 'en', 'Starting Point (optional)'),
('start_location_placeholder', 'en', 'Ex: Train station, Main square...'),
('history', 'en', 'History'),
('culture', 'en', 'Culture'),
('nature', 'en', 'Nature'),
('gastronomy', 'en', 'Gastronomy'),
('architecture', 'en', 'Architecture'),
('art', 'en', 'Art'),
('shopping', 'en', 'Shopping'),
('nightlife', 'en', 'Nightlife')
ON CONFLICT (key, language) DO UPDATE SET
value = EXCLUDED.value,
updated_at = now();

-- German translations
INSERT INTO ui_translations (key, language, value) VALUES
('desired_duration', 'de', 'Gewünschte Dauer'),
('choose_duration', 'de', 'Dauer wählen'),
('1_hour', 'de', '1 Stunde'),
('2_hours', 'de', '2 Stunden'),
('3_hours', 'de', '3 Stunden'),
('4_hours', 'de', '4 Stunden'),
('full_day', 'de', 'Ganzer Tag'),
('interests', 'de', 'Interessen'),
('difficulty_level', 'de', 'Schwierigkeitsgrad'),
('choose_difficulty', 'de', 'Schwierigkeit wählen'),
('easy_walk', 'de', 'Einfach - Gemütlicher Spaziergang'),
('moderate_walk', 'de', 'Mäßig - Aktiver Spaziergang'),
('difficult_hike', 'de', 'Schwierig - Wanderung'),
('group_size', 'de', 'Gruppengröße'),
('optional', 'de', 'Optional'),
('solo', 'de', 'Allein'),
('couple', 'de', 'Paar'),
('family', 'de', 'Familie'),
('group', 'de', 'Gruppe'),
('start_location', 'de', 'Startpunkt (optional)'),
('start_location_placeholder', 'de', 'Z.B.: Bahnhof, Hauptplatz...'),
('history', 'de', 'Geschichte'),
('culture', 'de', 'Kultur'),
('nature', 'de', 'Natur'),
('gastronomy', 'de', 'Gastronomie'),
('architecture', 'de', 'Architektur'),
('art', 'de', 'Kunst'),
('shopping', 'de', 'Einkaufen'),
('nightlife', 'de', 'Nachtleben')
ON CONFLICT (key, language) DO UPDATE SET
value = EXCLUDED.value,
updated_at = now();