-- Add JourneyOverview translations
INSERT INTO ui_translations (key, language, value) VALUES
-- JourneyOverview translations - French
('journey.overview.duration', 'fr', 'Durée'),
('journey.overview.distance', 'fr', 'Distance'),
('journey.overview.points', 'fr', 'Points'),
('journey.overview.statistics', 'fr', 'Statistiques du Parcours'),
('journey.overview.estimated_time', 'fr', 'Temps estimé'),
('journey.overview.total_distance', 'fr', 'Distance totale'),
('journey.overview.possible_points', 'fr', 'Points possibles'),
('journey.overview.points_info', 'fr', 'Gagnez des points à chaque étape complétée !'),
('journey.overview.steps_preview', 'fr', 'Aperçu des Étapes'),
('journey.overview.and', 'fr', 'et'),
('journey.overview.other_steps', 'fr', 'autres étapes'),
('journey.overview.ready_for_adventure', 'fr', 'Prêt pour l''Aventure ?'),
('journey.overview.adventure_description', 'fr', 'Commencez ce parcours maintenant et découvrez des lieux incroyables tout en gagnant des points !'),
('journey.overview.starting', 'fr', 'Démarrage en cours...'),
('journey.overview.start_adventure', 'fr', 'Commencer l''Aventure'),
('journey.overview.location_active', 'fr', 'Géolocalisation active'),
('journey.overview.login_to_participate', 'fr', 'Connectez-vous pour Participer'),
('journey.overview.login_description', 'fr', 'Créez votre compte pour commencer ce parcours, gagner des points et débloquer des récompenses !'),
('journey.overview.login_signup', 'fr', 'Se Connecter / S''inscrire'),

-- JourneyOverview translations - English
('journey.overview.duration', 'en', 'Duration'),
('journey.overview.distance', 'en', 'Distance'),
('journey.overview.points', 'en', 'Points'),
('journey.overview.statistics', 'en', 'Journey Statistics'),
('journey.overview.estimated_time', 'en', 'Estimated time'),
('journey.overview.total_distance', 'en', 'Total distance'),
('journey.overview.possible_points', 'en', 'Possible points'),
('journey.overview.points_info', 'en', 'Earn points at each completed step!'),
('journey.overview.steps_preview', 'en', 'Steps Preview'),
('journey.overview.and', 'en', 'and'),
('journey.overview.other_steps', 'en', 'other steps'),
('journey.overview.ready_for_adventure', 'en', 'Ready for Adventure?'),
('journey.overview.adventure_description', 'en', 'Start this journey now and discover incredible places while earning points!'),
('journey.overview.starting', 'en', 'Starting...'),
('journey.overview.start_adventure', 'en', 'Start Adventure'),
('journey.overview.location_active', 'en', 'Geolocation active'),
('journey.overview.login_to_participate', 'en', 'Log in to Participate'),
('journey.overview.login_description', 'en', 'Create your account to start this journey, earn points and unlock rewards!'),
('journey.overview.login_signup', 'en', 'Sign In / Sign Up'),

-- JourneyOverview translations - German
('journey.overview.duration', 'de', 'Dauer'),
('journey.overview.distance', 'de', 'Entfernung'),
('journey.overview.points', 'de', 'Punkte'),
('journey.overview.statistics', 'de', 'Reise-Statistiken'),
('journey.overview.estimated_time', 'de', 'Geschätzte Zeit'),
('journey.overview.total_distance', 'de', 'Gesamtentfernung'),
('journey.overview.possible_points', 'de', 'Mögliche Punkte'),
('journey.overview.points_info', 'de', 'Verdienen Sie Punkte bei jedem abgeschlossenen Schritt!'),
('journey.overview.steps_preview', 'de', 'Schritte Vorschau'),
('journey.overview.and', 'de', 'und'),
('journey.overview.other_steps', 'de', 'weitere Schritte'),
('journey.overview.ready_for_adventure', 'de', 'Bereit für das Abenteuer?'),
('journey.overview.adventure_description', 'de', 'Starten Sie diese Reise jetzt und entdecken Sie unglaubliche Orte während Sie Punkte sammeln!'),
('journey.overview.starting', 'de', 'Wird gestartet...'),
('journey.overview.start_adventure', 'de', 'Abenteuer Starten'),
('journey.overview.location_active', 'de', 'Geolokalisierung aktiv'),
('journey.overview.login_to_participate', 'de', 'Anmelden zum Teilnehmen'),
('journey.overview.login_description', 'de', 'Erstellen Sie Ihr Konto, um diese Reise zu beginnen, Punkte zu sammeln und Belohnungen freizuschalten!'),
('journey.overview.login_signup', 'de', 'Anmelden / Registrieren')
ON CONFLICT (key, language) DO UPDATE SET 
value = EXCLUDED.value,
updated_at = now();