-- Supprimer les traductions existantes pour les réinsérer
DELETE FROM ui_translations;

-- Insérer toutes les traductions pour l'interface utilisateur
INSERT INTO ui_translations (key, language, value) VALUES
-- Navigation et interface générale
('home', 'fr', 'Accueil'),
('home', 'en', 'Home'),
('home', 'de', 'Startseite'),
('explore', 'fr', 'Explorer'),
('explore', 'en', 'Explore'),
('explore', 'de', 'Erkunden'),
('my_journeys', 'fr', 'Mes Parcours'),
('my_journeys', 'en', 'My Journeys'),
('my_journeys', 'de', 'Meine Routen'),
('rewards', 'fr', 'Récompenses'),
('rewards', 'en', 'Rewards'),
('rewards', 'de', 'Belohnungen'),
('profile', 'fr', 'Profil'),
('profile', 'en', 'Profile'),
('profile', 'de', 'Profil'),

-- Générateur de parcours IA
('generate_journey', 'fr', 'Générer un Parcours'),
('generate_journey', 'en', 'Generate Journey'),
('generate_journey', 'de', 'Route Generieren'),
('ai_journey_generator', 'fr', 'Générateur IA'),
('ai_journey_generator', 'en', 'AI Generator'),
('ai_journey_generator', 'de', 'KI-Generator'),

-- Page d'accueil
('discover_intelligent_tourism', 'fr', 'Découvrez le Tourisme Intelligent'),
('discover_intelligent_tourism', 'en', 'Discover Intelligent Tourism'),
('discover_intelligent_tourism', 'de', 'Entdecken Sie den Intelligenten Tourismus'),
('explore_destinations_gamified', 'fr', 'Explorez vos destinations préférées avec des parcours gamifiés, gagnez des points et débloquez des récompenses exclusives.'),
('explore_destinations_gamified', 'en', 'Explore your favorite destinations with gamified routes, earn points and unlock exclusive rewards.'),
('explore_destinations_gamified', 'de', 'Erkunden Sie Ihre Lieblingsdestinationen mit spielerischen Routen, sammeln Sie Punkte und schalten Sie exklusive Belohnungen frei.'),
('start_adventure', 'fr', 'Commencer l''Aventure'),
('start_adventure', 'en', 'Start Adventure'),
('start_adventure', 'de', 'Abenteuer Beginnen'),

-- Fonctionnalités
('unique_experience', 'fr', 'Une Expérience Unique'),
('unique_experience', 'en', 'A Unique Experience'),
('unique_experience', 'de', 'Ein Einzigartiges Erlebnis'),
('transform_exploration', 'fr', 'CIARA transforme votre façon d''explorer en combinant technologie et découverte locale'),
('transform_exploration', 'en', 'CIARA transforms how you explore by combining technology and local discovery'),
('transform_exploration', 'de', 'CIARA verwandelt Ihre Art zu erkunden, indem es Technologie und lokale Entdeckungen kombiniert'),
('interactive_routes', 'fr', 'Parcours Interactifs'),
('interactive_routes', 'en', 'Interactive Routes'),
('interactive_routes', 'de', 'Interaktive Routen'),
('discover_destination_gamified', 'fr', 'Découvrez votre destination avec des parcours gamifiés et personnalisés'),
('discover_destination_gamified', 'en', 'Discover your destination with gamified and personalized routes'),
('discover_destination_gamified', 'de', 'Entdecken Sie Ihr Reiseziel mit spielerischen und personalisierten Routen'),
('reward_system', 'fr', 'Système de Récompenses'),
('reward_system', 'en', 'Reward System'),
('reward_system', 'de', 'Belohnungssystem'),
('earn_points_unlock_benefits', 'fr', 'Gagnez des points et débloquez des avantages chez nos partenaires locaux'),
('earn_points_unlock_benefits', 'en', 'Earn points and unlock benefits from our local partners'),
('earn_points_unlock_benefits', 'de', 'Sammeln Sie Punkte und schalten Sie Vorteile bei unseren lokalen Partnern frei'),
('personalized_ai', 'fr', 'IA Personnalisée'),
('personalized_ai', 'en', 'Personalized AI'),
('personalized_ai', 'de', 'Personalisierte KI'),
('intelligent_recommendations', 'fr', 'Des recommandations intelligentes basées sur vos préférences'),
('intelligent_recommendations', 'en', 'Intelligent recommendations based on your preferences'),
('intelligent_recommendations', 'de', 'Intelligente Empfehlungen basierend auf Ihren Vorlieben'),
('local_community', 'fr', 'Communauté Locale'),
('local_community', 'en', 'Local Community'),
('local_community', 'de', 'Lokale Gemeinschaft'),
('connect_explorers_locals', 'fr', 'Connectez-vous avec d''autres explorateurs et les habitants'),
('connect_explorers_locals', 'en', 'Connect with other explorers and locals'),
('connect_explorers_locals', 'de', 'Vernetzen Sie sich mit anderen Entdeckern und Einheimischen'),

-- Destinations
('available_destinations', 'fr', 'Destinations Disponibles'),
('available_destinations', 'en', 'Available Destinations'),
('available_destinations', 'de', 'Verfügbare Reiseziele'),
('each_destination_unique', 'fr', 'Chaque destination offre une expérience unique avec des parcours sur mesure'),
('each_destination_unique', 'en', 'Each destination offers a unique experience with custom routes'),
('each_destination_unique', 'de', 'Jedes Reiseziel bietet ein einzigartiges Erlebnis mit maßgeschneiderten Routen'),
('sion_description', 'fr', 'Capitale historique du Valais'),
('sion_description', 'en', 'Historic capital of Valais'),
('sion_description', 'de', 'Historische Hauptstadt des Wallis'),
('lausanne_description', 'fr', 'Ville olympique au bord du lac Léman'),
('lausanne_description', 'en', 'Olympic city on Lake Geneva'),
('lausanne_description', 'de', 'Olympische Stadt am Genfersee'),
('geneva_description', 'fr', 'Ville internationale et cosmopolite'),
('geneva_description', 'en', 'International and cosmopolitan city'),
('geneva_description', 'de', 'Internationale und kosmopolitische Stadt'),
('explore_now', 'fr', 'Explorer maintenant'),
('explore_now', 'en', 'Explore now'),
('explore_now', 'de', 'Jetzt erkunden'),

-- Call to action
('ready_for_adventure', 'fr', 'Prêt pour l''Aventure ?'),
('ready_for_adventure', 'en', 'Ready for Adventure?'),
('ready_for_adventure', 'de', 'Bereit für das Abenteuer?'),
('join_thousands_explorers', 'fr', 'Rejoignez des milliers d''explorateurs qui ont déjà découvert une nouvelle façon de voyager'),
('join_thousands_explorers', 'en', 'Join thousands of explorers who have already discovered a new way to travel'),
('join_thousands_explorers', 'de', 'Schließen Sie sich Tausenden von Entdeckern an, die bereits eine neue Art des Reisens entdeckt haben'),

-- Authentification
('login', 'fr', 'Se connecter'),
('login', 'en', 'Login'),
('login', 'de', 'Anmelden'),
('register', 'fr', 'S''inscrire'),
('register', 'en', 'Register'),
('register', 'de', 'Registrieren'),
('logout', 'fr', 'Se déconnecter'),
('logout', 'en', 'Logout'),
('logout', 'de', 'Abmelden')
ON CONFLICT (key, language) DO UPDATE SET value = EXCLUDED.value;