
-- Ajouter les traductions manquantes pour l'interface utilisateur
INSERT INTO ui_translations (key, language, value) VALUES
-- Navigation et boutons de base
('login', 'fr', 'Connexion'),
('login', 'en', 'Login'),
('login', 'de', 'Anmelden'),
('register', 'fr', 'S''inscrire'),
('register', 'en', 'Register'),
('register', 'de', 'Registrieren'),
('logout', 'fr', 'Déconnexion'),
('logout', 'en', 'Logout'),
('logout', 'de', 'Abmelden'),

-- Pages principales
('faq', 'fr', 'FAQ'),
('faq', 'en', 'FAQ'),
('faq', 'de', 'FAQ'),
('contact', 'fr', 'Contact'),
('contact', 'en', 'Contact'),
('contact', 'de', 'Kontakt'),
('privacy', 'fr', 'Confidentialité'),
('privacy', 'en', 'Privacy'),
('privacy', 'de', 'Datenschutz'),
('terms', 'fr', 'Conditions'),
('terms', 'en', 'Terms'),
('terms', 'de', 'Bedingungen'),
('legal', 'fr', 'Mentions légales'),
('legal', 'en', 'Legal Notice'),
('legal', 'de', 'Impressum'),

-- Footer
('footer_company_description', 'fr', 'Découvrez le tourisme intelligent avec des parcours gamifiés qui transforment chaque destination en aventure interactive.'),
('footer_company_description', 'en', 'Discover smart tourism with gamified routes that transform every destination into an interactive adventure.'),
('footer_company_description', 'de', 'Entdecken Sie intelligenten Tourismus mit spielerischen Routen, die jedes Reiseziel in ein interaktives Abenteuer verwandeln.'),
('footer_quick_links', 'fr', 'Liens rapides'),
('footer_quick_links', 'en', 'Quick Links'),
('footer_quick_links', 'de', 'Schnellzugriff'),
('footer_support', 'fr', 'Support'),
('footer_support', 'en', 'Support'),
('footer_support', 'de', 'Support'),
('footer_legal', 'fr', 'Légal'),
('footer_legal', 'en', 'Legal'),
('footer_legal', 'de', 'Rechtliches'),
('footer_rights', 'fr', 'Tous droits réservés.'),
('footer_rights', 'en', 'All rights reserved.'),
('footer_rights', 'de', 'Alle Rechte vorbehalten.'),
('our_cities', 'fr', 'Nos villes'),
('our_cities', 'en', 'Our Cities'),
('our_cities', 'de', 'Unsere Städte'),
('cookies', 'fr', 'Cookies'),
('cookies', 'en', 'Cookies'),
('cookies', 'de', 'Cookies'),

-- Page de sélection des villes
('choose_destination', 'fr', 'Choisissez Votre Destination'),
('choose_destination', 'en', 'Choose Your Destination'),
('choose_destination', 'de', 'Wählen Sie Ihr Reiseziel'),
('destination_subtitle', 'fr', 'Sélectionnez la ville que vous souhaitez explorer et découvrez des parcours personnalisés adaptés à vos envies.'),
('destination_subtitle', 'en', 'Select the city you want to explore and discover personalized routes tailored to your desires.'),
('destination_subtitle', 'de', 'Wählen Sie die Stadt, die Sie erkunden möchten, und entdecken Sie personalisierte Routen, die auf Ihre Wünsche zugeschnitten sind.'),
('search_placeholder', 'fr', 'Rechercher une ville, un pays...'),
('search_placeholder', 'en', 'Search for a city, country...'),
('search_placeholder', 'de', 'Stadt, Land suchen...'),
('filter_by_country', 'fr', 'Filtrer par pays'),
('filter_by_country', 'en', 'Filter by country'),
('filter_by_country', 'de', 'Nach Land filtern'),
('all_countries', 'fr', 'Tous les pays'),
('all_countries', 'en', 'All countries'),
('all_countries', 'de', 'Alle Länder'),
('destinations_available', 'fr', 'destination(s) disponible(s)'),
('destinations_available', 'en', 'destination(s) available'),
('destinations_available', 'de', 'Reiseziel(e) verfügbar'),
('explore_with_confidence', 'fr', 'Explorez nos destinations avec confiance'),
('explore_with_confidence', 'en', 'Explore our destinations with confidence'),
('explore_with_confidence', 'de', 'Entdecken Sie unsere Reiseziele mit Vertrauen'),
('journeys_count', 'fr', 'parcours'),
('journeys_count', 'en', 'journeys'),
('journeys_count', 'de', 'Touren'),
('explore_city', 'fr', 'Explorer'),
('explore_city', 'en', 'Explore'),
('explore_city', 'de', 'Erkunden'),
('no_destination_found', 'fr', 'Aucune destination trouvée'),
('no_destination_found', 'en', 'No destination found'),
('no_destination_found', 'de', 'Kein Reiseziel gefunden'),
('modify_search_criteria', 'fr', 'Essayez de modifier vos critères de recherche ou explorez toutes nos destinations.'),
('modify_search_criteria', 'en', 'Try modifying your search criteria or explore all our destinations.'),
('modify_search_criteria', 'de', 'Versuchen Sie, Ihre Suchkriterien zu ändern oder erkunden Sie alle unsere Reiseziele.'),
('reset_filters', 'fr', 'Réinitialiser les filtres'),
('reset_filters', 'en', 'Reset filters'),
('reset_filters', 'de', 'Filter zurücksetzen'),
('how_it_works', 'fr', 'Comment ça fonctionne ?'),
('how_it_works', 'en', 'How does it work?'),
('how_it_works', 'de', 'Wie funktioniert es?'),
('how_it_works_description', 'fr', 'Choisissez votre ville, créez votre profil d''explorateur, et laissez notre IA vous proposer des parcours personnalisés selon vos préférences et votre niveau de forme physique.'),
('how_it_works_description', 'en', 'Choose your city, create your explorer profile, and let our AI suggest personalized routes based on your preferences and fitness level.'),
('how_it_works_description', 'de', 'Wählen Sie Ihre Stadt, erstellen Sie Ihr Entdecker-Profil und lassen Sie unsere KI personalisierte Routen basierend auf Ihren Vorlieben und Ihrem Fitnesslevel vorschlagen.'),
('step_select', 'fr', 'Sélectionnez'),
('step_select', 'en', 'Select'),
('step_select', 'de', 'Auswählen'),
('step_select_desc', 'fr', 'Choisissez votre destination'),
('step_select_desc', 'en', 'Choose your destination'),
('step_select_desc', 'de', 'Wählen Sie Ihr Reiseziel'),
('step_explore_desc', 'fr', 'Suivez des parcours gamifiés'),
('step_explore_desc', 'en', 'Follow gamified routes'),
('step_explore_desc', 'de', 'Folgen Sie spielerischen Routen'),
('step_earn', 'fr', 'Gagnez'),
('step_earn', 'en', 'Earn'),
('step_earn', 'de', 'Verdienen'),
('step_earn_desc', 'fr', 'Collectez points et récompenses'),
('step_earn_desc', 'en', 'Collect points and rewards'),
('step_earn_desc', 'de', 'Sammeln Sie Punkte und Belohnungen'),

-- FAQ Page
('faq_title', 'fr', 'Comment pouvons-nous vous aider ?'),
('faq_title', 'en', 'How can we help you?'),
('faq_title', 'de', 'Wie können wir Ihnen helfen?'),
('faq_subtitle', 'fr', 'Trouvez rapidement les réponses à vos questions les plus fréquentes'),
('faq_subtitle', 'en', 'Quickly find answers to your most frequently asked questions'),
('faq_subtitle', 'de', 'Finden Sie schnell Antworten auf Ihre häufigsten Fragen'),
('faq_category_usage', 'fr', 'Utilisation'),
('faq_category_usage', 'en', 'Usage'),
('faq_category_usage', 'de', 'Verwendung'),
('faq_category_rewards', 'fr', 'Points et Récompenses'),
('faq_category_rewards', 'en', 'Points and Rewards'),
('faq_category_rewards', 'de', 'Punkte und Belohnungen'),
('faq_category_technical', 'fr', 'Technique'),
('faq_category_technical', 'en', 'Technical'),
('faq_category_technical', 'de', 'Technisch'),
('faq_category_ai', 'fr', 'Intelligence Artificielle'),
('faq_category_ai', 'en', 'Artificial Intelligence'),
('faq_category_ai', 'de', 'Künstliche Intelligenz'),
('faq_no_answer', 'fr', 'Vous ne trouvez pas votre réponse ?'),
('faq_no_answer', 'en', 'Can''t find your answer?'),
('faq_no_answer', 'de', 'Finden Sie Ihre Antwort nicht?'),
('faq_contact_us', 'fr', 'Notre équipe est là pour vous aider !'),
('faq_contact_us', 'en', 'Our team is here to help you!'),
('faq_contact_us', 'de', 'Unser Team ist da, um Ihnen zu helfen!'),
('contact_us', 'fr', 'Nous contacter'),
('contact_us', 'en', 'Contact Us'),
('contact_us', 'de', 'Kontaktieren Sie uns')

ON CONFLICT (key, language) DO NOTHING;

-- Mettre à jour la fonction AI chat pour supporter les langues
CREATE OR REPLACE FUNCTION get_ai_system_prompt(lang TEXT DEFAULT 'fr')
RETURNS TEXT
LANGUAGE sql
STABLE
AS $$
  SELECT CASE lang
    WHEN 'en' THEN 'You are CIARA, the intelligent assistant of the CIARA gamified tourism platform. You specialize in helping travelers and explorers. Respond in English.'
    WHEN 'de' THEN 'Sie sind CIARA, der intelligente Assistent der CIARA gamifizierten Tourismusplattform. Sie sind auf die Hilfe für Reisende und Entdecker spezialisiert. Antworten Sie auf Deutsch.'
    ELSE 'Tu es CIARA, l''assistant intelligent de la plateforme de tourisme gamifié CIARA. Tu es spécialisé dans l''aide aux voyageurs et explorateurs. Réponds en français.'
  END;
$$;
